import { defineManifest } from '@template/modules'

export default defineManifest({
  id: 'docs-module',
  name: 'Documentação',
  description:
    'Documentação interna integrada — guias, referência de API e changelog da plataforma',
  version: '1.0.0',
  category: 'optional',
  enabled: false,
  order: 40,
  dependencies: ['auth'],
  routes: ['/docs-interno', '/docs-interno/api', '/docs-interno/changelog'],
  apiRoutes: ['/api/docs'],
  requiredTables: [],
  envVars: [],
  featureFlags: ['module.docs-module'],
  hooks: [],
  components: ['DocsPage', 'ApiDocsPage', 'ChangelogPage'],
  icon: 'BookOpen',
  path: '/docs-interno',
  roles: [],
  showInSidebar: true,
  group: 'Suporte',
  functions: [
    {
      id: 'docs-main',
      moduleId: 'docs-module',
      name: 'Documentação',
      subtitle: 'Guias e tutoriais',
      path: '/docs-interno',
      category: 'SUPORTE',
      enabled: true,
      order: 0,
      roles: [],
      tags: ['docs', 'guias'],
    },
    {
      id: 'docs-api',
      moduleId: 'docs-module',
      name: 'Referência de API',
      subtitle: 'Endpoints e contratos',
      path: '/docs-interno/api',
      category: 'SUPORTE',
      enabled: true,
      order: 1,
      roles: [],
      tags: ['api', 'referencia'],
    },
    {
      id: 'docs-changelog',
      moduleId: 'docs-module',
      name: 'Changelog',
      subtitle: 'Histórico de versões',
      path: '/docs-interno/changelog',
      category: 'SUPORTE',
      enabled: true,
      order: 2,
      roles: [],
      tags: ['changelog', 'versoes'],
    },
  ],
})
