import { defineManifest } from '@template/modules'

export default defineManifest({
  id: 'observability',
  name: 'Observabilidade',
  description:
    'Métricas de uso, logs de aplicação, health check e qualidade de dados em tempo real',
  version: '1.0.0',
  category: 'optional',
  enabled: false,
  order: 15,
  dependencies: ['auth', 'admin'],
  routes: [
    '/admin/observability',
    '/admin/observability/metricas',
    '/admin/observability/logs',
    '/admin/observability/health',
    '/admin/observability/qualidade',
  ],
  apiRoutes: ['/api/observability', '/api/metrics', '/api/health'],
  requiredTables: ['app_metrics', 'app_logs'],
  envVars: [
    {
      key: 'OTEL_EXPORTER_OTLP_ENDPOINT',
      required: false,
      description: 'Endpoint OpenTelemetry para exportar traces',
    },
  ],
  featureFlags: ['module.observability'],
  hooks: ['useMetrics', 'useLogs', 'useHealth'],
  components: ['MetricsPage', 'LogsPage', 'HealthPage', 'DataQualityPage'],
  icon: 'Activity',
  path: '/admin/observability',
  roles: ['ADMIN', 'GESTOR'],
  showInSidebar: true,
  group: 'Operações',
  functions: [
    {
      id: 'observability-metrics',
      moduleId: 'observability',
      name: 'Métricas',
      subtitle: 'Uso e performance da plataforma',
      path: '/admin/observability/metricas',
      category: 'OPERACOES',
      enabled: true,
      order: 0,
      roles: ['ADMIN', 'GESTOR'],
      tags: ['metricas', 'performance'],
    },
    {
      id: 'observability-logs',
      moduleId: 'observability',
      name: 'Logs',
      subtitle: 'Logs de aplicação em tempo real',
      path: '/admin/observability/logs',
      category: 'OPERACOES',
      enabled: true,
      order: 1,
      roles: ['ADMIN'],
      tags: ['logs', 'debug'],
    },
    {
      id: 'observability-health',
      moduleId: 'observability',
      name: 'Health Check',
      subtitle: 'Status dos serviços',
      path: '/admin/observability/health',
      category: 'OPERACOES',
      enabled: true,
      order: 2,
      roles: ['ADMIN', 'GESTOR'],
      tags: ['health', 'status'],
    },
    {
      id: 'observability-quality',
      moduleId: 'observability',
      name: 'Qualidade de Dados',
      subtitle: 'Integridade e consistência',
      path: '/admin/observability/qualidade',
      category: 'OPERACOES',
      enabled: true,
      order: 3,
      roles: ['ADMIN'],
      tags: ['qualidade', 'dados'],
    },
  ],
})
