import { defineManifest } from '@template/modules'

export default defineManifest({
  id: 'lgpd',
  name: 'LGPD',
  description:
    'Privacidade e proteção de dados — consentimento, portabilidade, exclusão e auditoria LGPD',
  version: '1.0.0',
  category: 'optional',
  enabled: false,
  order: 30,
  dependencies: ['auth', 'settings'],
  routes: ['/lgpd', '/lgpd/consentimento', '/lgpd/meus-dados'],
  apiRoutes: ['/api/lgpd'],
  requiredTables: ['consent_records', 'data_export_requests'],
  envVars: [],
  featureFlags: ['module.lgpd'],
  hooks: ['useConsent', 'useMyData'],
  components: ['LGPDPage', 'ConsentPage', 'MyDataPage'],
  icon: 'Shield',
  path: '/lgpd',
  roles: [],
  showInSidebar: true,
  group: 'Privacidade',
  functions: [
    {
      id: 'lgpd-main',
      moduleId: 'lgpd',
      name: 'Privacidade',
      subtitle: 'Visão geral LGPD',
      path: '/lgpd',
      category: 'PRIVACIDADE',
      enabled: true,
      order: 0,
      roles: [],
      tags: ['lgpd', 'privacidade'],
    },
    {
      id: 'lgpd-consent',
      moduleId: 'lgpd',
      name: 'Consentimento',
      subtitle: 'Gerenciar consentimentos',
      path: '/lgpd/consentimento',
      category: 'PRIVACIDADE',
      enabled: true,
      order: 1,
      roles: [],
      tags: ['consentimento', 'lgpd'],
    },
    {
      id: 'lgpd-mydata',
      moduleId: 'lgpd',
      name: 'Meus Dados',
      subtitle: 'Exportar ou solicitar exclusão',
      path: '/lgpd/meus-dados',
      category: 'PRIVACIDADE',
      enabled: true,
      order: 2,
      roles: [],
      tags: ['portabilidade', 'exclusao'],
    },
  ],
})
