import { defineManifest } from '@template/modules'

export default defineManifest({
  id: 'etl',
  name: 'ETL',
  description: 'Pipeline de importação de dados — catálogo de fontes, jobs, qualidade e logs',
  version: '1.0.0',
  category: 'optional',
  enabled: false,
  order: 20,
  dependencies: ['auth', 'admin'],
  routes: ['/admin/etl', '/admin/etl/catalogo', '/admin/etl/qualidade', '/admin/etl/logs'],
  apiRoutes: ['/api/etl'],
  requiredTables: ['etl_jobs', 'etl_data_sources', 'etl_quality_reports'],
  envVars: [],
  featureFlags: ['module.etl'],
  hooks: ['useETLJobs', 'useDataSources', 'useDataQuality'],
  components: [
    'ETLPage',
    'ETLCatalogPage',
    'ETLQualityPage',
    'ETLLogsPage',
    'DataSourceCard',
    'JobProgress',
    'QualityBadge',
  ],
  icon: 'Database',
  path: '/admin/etl',
  roles: ['ADMIN', 'GESTOR'],
  showInSidebar: true,
  group: 'Dados',
  functions: [
    {
      id: 'etl-jobs',
      moduleId: 'etl',
      name: 'Jobs de Importação',
      subtitle: 'Monitorar e executar pipelines',
      path: '/admin/etl',
      category: 'DADOS',
      enabled: true,
      order: 0,
      roles: ['ADMIN', 'GESTOR'],
      tags: ['etl', 'importacao', 'jobs'],
    },
    {
      id: 'etl-catalog',
      moduleId: 'etl',
      name: 'Catálogo de Fontes',
      subtitle: 'Fontes de dados cadastradas',
      path: '/admin/etl/catalogo',
      category: 'DADOS',
      enabled: true,
      order: 1,
      roles: ['ADMIN', 'GESTOR'],
      tags: ['catalogo', 'fontes'],
    },
    {
      id: 'etl-quality',
      moduleId: 'etl',
      name: 'Qualidade de Dados',
      subtitle: 'Relatórios e métricas de qualidade',
      path: '/admin/etl/qualidade',
      category: 'DADOS',
      enabled: true,
      order: 2,
      roles: ['ADMIN', 'GESTOR'],
      tags: ['qualidade', 'metricas'],
    },
    {
      id: 'etl-logs',
      moduleId: 'etl',
      name: 'Logs',
      subtitle: 'Histórico de execuções',
      path: '/admin/etl/logs',
      category: 'DADOS',
      enabled: true,
      order: 3,
      roles: ['ADMIN'],
      tags: ['logs', 'historico'],
    },
  ],
})
