#!/usr/bin/env node
/**
 * CLI Scaffolding — Generate new modules/functions
 * Usage:
 *   node scripts/scaffold-module.mjs <module-name> [--functions func1,func2]
 *
 * Example:
 *   node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WEB_ROOT = path.resolve(__dirname, '..', 'apps', 'web')

function kebabCase(str) {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

function pascalCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function titleCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function createDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
    console.log(`  📁 Created ${path.relative(process.cwd(), dirPath)}`)
  }
}

function writeFile(filePath, content) {
  if (fs.existsSync(filePath)) {
    console.log(`  ⚠️  Skipped (exists): ${path.relative(process.cwd(), filePath)}`)
    return
  }
  fs.writeFileSync(filePath, content, 'utf-8')
  console.log(`  ✅ Created ${path.relative(process.cwd(), filePath)}`)
}

// ── Manifest + API Route + modules.config Templates ─────────

function manifestTemplate(name) {
  const kebab = kebabCase(name)
  const title = titleCase(name)
  return `import { defineManifest } from '@template/modules'

export default defineManifest({
  id: '${kebab}',
  name: '${title}',
  description: 'Modulo ${title}',
  version: '1.0.0',
  category: 'optional',
  enabled: false,
  order: 50,
  dependencies: ['auth'],
  routes: ['/${kebab}'],
  apiRoutes: ['/api/${kebab}'],
  requiredTables: ['${kebab.replace(/-/g, '_')}'],
  envVars: [],
  featureFlags: ['module.${kebab}'],
  hooks: ['use${pascalCase(name)}'],
  components: [],
  icon: 'Box',
  path: '/${kebab}',
  roles: [],
  showInSidebar: true,
  group: 'Principal',
  functions: [
    {
      id: '${kebab}-main',
      moduleId: '${kebab}',
      name: '${title}',
      subtitle: 'Pagina principal',
      path: '/${kebab}',
      category: 'OPERACIONAL',
      enabled: true,
      order: 0,
      roles: [],
      tags: ['${kebab}'],
    },
  ],
})
`
}

function apiRouteTemplate(name) {
  const kebab = kebabCase(name)
  const pascal = pascalCase(name)
  return `/**
 * GET  /api/${kebab}     — lista registros
 * POST /api/${kebab}     — cria novo registro
 *
 * Auto-generated by scaffold-module
 */
import type { NextRequest } from 'next/server'
import { withModuleGuard } from '@/lib/api-module-guard'
import { withApiLog } from '@/lib/logger'
import {
  ok,
  created,
  badRequest,
  unauthorized,
  tooManyRequests,
  serverError,
} from '@/lib/api-response'
import { rateLimit, getClientIp } from '@/lib/rate-limit'
import { getAuthGateway } from '@/lib/data'

export const dynamic = 'force-dynamic'

export const GET = withModuleGuard(
  '${kebab}',
  withApiLog('${kebab}', async function GET(request: NextRequest) {
    const ip = getClientIp(request.headers)
    const { success } = rateLimit(ip, { windowMs: 60_000, max: 120 })
    if (!success) return tooManyRequests()

    const { user, error } = await getAuthGateway().getUser()
    if (error || !user) return unauthorized()

    try {
      // TODO: implementar listagem de ${kebab}
      return ok([])
    } catch (err) {
      console.error('[${kebab}/GET]', err)
      return serverError()
    }
  })
)

export const POST = withModuleGuard(
  '${kebab}',
  withApiLog('${kebab}', async function POST(request: NextRequest) {
    const ip = getClientIp(request.headers)
    const { success } = rateLimit(ip, { windowMs: 60_000, max: 30 })
    if (!success) return tooManyRequests()

    const { user, error } = await getAuthGateway().getUser()
    if (error || !user) return unauthorized()

    let body: unknown
    try {
      body = await request.json()
    } catch {
      return badRequest('Invalid JSON body')
    }

    try {
      // TODO: implementar criacao de ${kebab}
      return created(body)
    } catch (err) {
      console.error('[${kebab}/POST]', err)
      return serverError()
    }
  })
)
`
}

/**
 * Adiciona entry ao modules.config.ts como enabled: false.
 * Retorna true se adicionou, false se ja existia.
 */
function addToModulesConfig(name) {
  const kebab = kebabCase(name)
  const configPath = path.join(WEB_ROOT, 'modules.config.ts')

  if (!fs.existsSync(configPath)) {
    console.log(`  ⚠️  modules.config.ts nao encontrado — pule manualmente`)
    return false
  }

  let content = fs.readFileSync(configPath, 'utf-8')

  // Verificar se ja existe
  if (content.includes(`'${kebab}'`) || content.includes(`"${kebab}"`)) {
    console.log(`  ⚠️  modules.config.ts ja contem '${kebab}'`)
    return false
  }

  // Inserir antes do fechamento do objeto (ultima })
  const lastBrace = content.lastIndexOf('}')
  if (lastBrace === -1) {
    console.log(`  ⚠️  modules.config.ts formato inesperado`)
    return false
  }

  // Encontrar a ultima entry real (antes do fechamento)
  const beforeBrace = content.slice(0, lastBrace).trimEnd()
  const needsComma = !beforeBrace.endsWith(',')

  const newEntry = `${needsComma ? ',' : ''}\n\n  // ── Gerado por scaffold-module ──────────────────────────────\n  '${kebab}': { enabled: false },`
  content = content.slice(0, lastBrace) + newEntry + '\n' + content.slice(lastBrace)

  fs.writeFileSync(configPath, content, 'utf-8')
  console.log(`  ✅ Adicionado '${kebab}' ao modules.config.ts (enabled: false)`)
  return true
}

// ── Templates ────────────────────────────────────────────────

function pageTemplate(name) {
  const pascal = pascalCase(name)
  const title = titleCase(name)
  return `/**
 * ${pascal}Page — Auto-generated by scaffold-module
 */
export default function ${pascal}Page() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">${title}</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">
          Pagina do modulo ${title}
        </p>
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">
          Conteudo do modulo ${title}. Implemente sua logica aqui.
        </p>
      </div>
    </div>
  )
}
`
}

function testTemplate(name) {
  const pascal = pascalCase(name)
  return `import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import ${pascal}Page from './${pascal}Page'

describe('${pascal}Page', () => {
  it('renders page title', () => {
    render(<${pascal}Page />)
    expect(screen.getByText('${titleCase(name)}')).toBeInTheDocument()
  })
})
`
}

function serviceTemplate(name) {
  const kebab = kebabCase(name)
  return `/**
 * ${pascalCase(name)} Service — API client
 * Auto-generated by scaffold-module
 */
import { apiClient } from '@template/shared'

const BASE = '/${kebab}'

export const ${kebabCase(name).replace(/-/g, '')}Service = {
  async list(params?: Record<string, string>) {
    const { data } = await apiClient.get(BASE, { params })
    return data
  },

  async getById(id: string) {
    const { data } = await apiClient.get(\`\${BASE}/\${id}\`)
    return data
  },

  async create(payload: Record<string, unknown>) {
    const { data } = await apiClient.post(BASE, payload)
    return data
  },

  async update(id: string, payload: Record<string, unknown>) {
    const { data } = await apiClient.patch(\`\${BASE}/\${id}\`, payload)
    return data
  },

  async remove(id: string) {
    const { data } = await apiClient.delete(\`\${BASE}/\${id}\`)
    return data
  },
}
`
}

function hookTemplate(name) {
  const pascal = pascalCase(name)
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1)
  const svcName = kebabCase(name).replace(/-/g, '')
  return `/**
 * use${pascal} — TanStack Query hooks (queries + mutations)
 * Auto-generated by scaffold-module
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { ${svcName}Service } from '@/services/${kebabCase(name)}'

const KEYS = {
  all: ['${camel}'] as const,
  list: (params?: Record<string, string>) => [...KEYS.all, 'list', params] as const,
  detail: (id: string | null) => [...KEYS.all, 'detail', id] as const,
}

export function use${pascal}List(params?: Record<string, string>) {
  return useQuery({
    queryKey: KEYS.list(params),
    queryFn: () => ${svcName}Service.list(params),
  })
}

export function use${pascal}ById(id: string | null) {
  return useQuery({
    queryKey: KEYS.detail(id),
    queryFn: () => ${svcName}Service.getById(id!),
    enabled: !!id,
  })
}

export function useCreate${pascal}() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (payload: Record<string, unknown>) => ${svcName}Service.create(payload),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: KEYS.all })
    },
  })
}

export function useUpdate${pascal}() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: ({ id, ...payload }: { id: string } & Record<string, unknown>) =>
      ${svcName}Service.update(id, payload),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: KEYS.all })
    },
  })
}

export function useDelete${pascal}() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => ${svcName}Service.remove(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: KEYS.all })
    },
  })
}
`
}

function schemaTemplate(name) {
  const pascal = pascalCase(name)
  return `/**
 * ${pascal} Zod schemas
 * Auto-generated by scaffold-module
 * Canonical source — re-export via @template/shared if needed cross-app.
 */
import { z } from 'zod'

export const ${pascal}CreateSchema = z.object({
  // Define your fields here
  name: z.string().min(1, 'Nome e obrigatorio').max(255).trim(),
})

export const ${pascal}UpdateSchema = ${pascal}CreateSchema.partial()

export type ${pascal}CreateInput = z.infer<typeof ${pascal}CreateSchema>
export type ${pascal}UpdateInput = z.infer<typeof ${pascal}UpdateSchema>
`
}

function functionPageTemplate(moduleName, funcName) {
  const modulePascal = pascalCase(moduleName)
  const funcPascal = pascalCase(funcName)
  const funcTitle = titleCase(funcName)
  return `/**
 * ${modulePascal} > ${funcPascal} — Auto-generated
 */
export default function ${modulePascal}${funcPascal}Page() {
  return (
    <div className="space-y-4">
      <h2 className="text-xl font-semibold text-gray-900 dark:text-white">${funcTitle}</h2>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">Conteudo de ${funcTitle}.</p>
      </div>
    </div>
  )
}
`
}

function e2eStubTemplate(name) {
  const kebab = kebabCase(name)
  const title = titleCase(name)
  return `import { test, expect } from '@playwright/test'

/**
 * E2E smoke test — ${title}
 * Auto-generated by scaffold-module
 */
test.describe('${title} module', () => {
  test('page loads and shows title', async ({ page }) => {
    await page.goto('/${kebab}')
    await expect(page.locator('h1, h2').first()).toContainText('${title}')
  })
})
`
}

/**
 * Auto-registra import e manifest no config/modules/index.ts.
 * Adiciona import statement + entry no ALL_MANIFESTS array.
 */
function addToModulesIndex(name) {
  const kebab = kebabCase(name)
  const camel = kebabCase(name).replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Manifest'
  const indexPath = path.join(WEB_ROOT, 'config', 'modules', 'index.ts')

  if (!fs.existsSync(indexPath)) {
    console.log(`  ⚠️  config/modules/index.ts nao encontrado`)
    return false
  }

  let content = fs.readFileSync(indexPath, 'utf-8')

  // Check if already registered
  if (content.includes(`'${kebab}.manifest'`) || content.includes(`"${kebab}.manifest"`)) {
    console.log(`  ⚠️  index.ts ja contem import de '${kebab}.manifest'`)
    return false
  }

  // Add import statement before ALL_MANIFESTS declaration
  const allManifestsLine = 'const ALL_MANIFESTS: ModuleManifest[] = ['
  const importLine = `import ${camel} from './${kebab}.manifest'\n`

  const allIdx = content.indexOf(allManifestsLine)
  if (allIdx === -1) {
    console.log(`  ⚠️  ALL_MANIFESTS nao encontrado em index.ts`)
    return false
  }

  // Insert import before the empty line preceding ALL_MANIFESTS
  content = content.slice(0, allIdx) + importLine + content.slice(allIdx)

  // Add to ALL_MANIFESTS array (before the closing bracket)
  const closingBracket = content.indexOf(']', content.indexOf(allManifestsLine))
  if (closingBracket === -1) {
    console.log(`  ⚠️  Formato inesperado de ALL_MANIFESTS`)
    return false
  }

  const beforeClose = content.slice(0, closingBracket).trimEnd()
  const needsComma = !beforeClose.endsWith(',')
  const entry = `${needsComma ? ',' : ''}\n  ${camel},\n`
  content = content.slice(0, closingBracket) + entry + content.slice(closingBracket)

  fs.writeFileSync(indexPath, content, 'utf-8')
  console.log(`  ✅ Auto-registrado '${kebab}' em config/modules/index.ts`)
  return true
}

// ── Copy from starter helper ──────────────────────────────────

const STARTERS_ROOT = path.resolve(__dirname, '..', 'packages', 'module-starters')

/**
 * Copia um módulo starter como base para o novo módulo,
 * renomeando IDs e variáveis para o novo nome.
 */
function copyFromStarter(starterId, newName) {
  const starterDir = path.join(STARTERS_ROOT, starterId)
  if (!fs.existsSync(starterDir)) {
    console.log(`  ⚠️  Starter '${starterId}' não encontrado em packages/module-starters/`)
    return false
  }

  const newKebab = kebabCase(newName)
  const newPascal = pascalCase(newName)
  const newTitle = titleCase(newName)

  console.log(`\n  📋 Copiando a partir do starter '${starterId}'...\n`)

  // Manifest
  const manifestSrc = path.join(starterDir, 'manifest.ts')
  if (fs.existsSync(manifestSrc)) {
    let content = fs.readFileSync(manifestSrc, 'utf-8')
    // Substituir referências ao starter pelo novo módulo
    content = content
      .replaceAll(`id: '${starterId}'`, `id: '${newKebab}'`)
      .replaceAll(`'${starterId}'`, `'${newKebab}'`)
      .replaceAll(`"${starterId}"`, `"${newKebab}"`)
      .replaceAll(`/${starterId}`, `/${newKebab}`)
      .replaceAll(`module.${starterId}`, `module.${newKebab}`)
    const manifestDst = path.join(WEB_ROOT, 'config', 'modules', `${newKebab}.manifest.ts`)
    writeFile(manifestDst, content)
  }

  // API route
  const apiSrc = path.join(starterDir, 'api', 'route.ts')
  if (fs.existsSync(apiSrc)) {
    let content = fs.readFileSync(apiSrc, 'utf-8')
    content = content.replaceAll(`'${starterId}'`, `'${newKebab}'`).replaceAll(`"${starterId}"`, `"${newKebab}"`)
    const apiDst = path.join(WEB_ROOT, 'app', 'api', newKebab, 'route.ts')
    createDir(path.dirname(apiDst))
    writeFile(apiDst, content)
  }

  // App pages
  const appSrc = path.join(starterDir, 'app')
  if (fs.existsSync(appSrc)) {
    const appDst = path.join(WEB_ROOT, 'app', '(authenticated)', newKebab)
    createDir(appDst)
    for (const file of fs.readdirSync(appSrc)) {
      const src = path.join(appSrc, file)
      let content = fs.readFileSync(src, 'utf-8')
      // Renomear classes/nomes nos componentes para o novo módulo
      content = content.replaceAll(pascalCase(starterId), newPascal).replaceAll(starterId, newKebab)
      writeFile(path.join(appDst, file), content)
    }
  }

  // Components
  const compSrc = path.join(starterDir, 'components')
  if (fs.existsSync(compSrc) && fs.readdirSync(compSrc).length > 0) {
    const compDst = path.join(WEB_ROOT, 'components', newKebab)
    createDir(compDst)
    for (const file of fs.readdirSync(compSrc)) {
      const src = path.join(compSrc, file)
      const content = fs.readFileSync(src, 'utf-8')
      writeFile(path.join(compDst, file), content)
    }
    console.log(`  💡 Componentes copiados em components/${newKebab}/ — ajuste imports`)
  }

  // Types
  const typesSrc = path.join(starterDir, 'types.ts')
  if (fs.existsSync(typesSrc)) {
    let content = fs.readFileSync(typesSrc, 'utf-8')
    content = content.replaceAll(pascalCase(starterId), newPascal)
    writeFile(path.join(WEB_ROOT, 'schemas', `${newKebab}.ts`), content)
  }

  // Migrations note
  const migrationsSrc = path.join(starterDir, 'migrations')
  if (fs.existsSync(migrationsSrc)) {
    console.log(`  💡 Migrations disponíveis em packages/module-starters/${starterId}/migrations/`)
    console.log(`     Copie para supabase/migrations/ e ajuste o número sequencial`)
  }

  return true
}

// ── Main ─────────────────────────────────────────────────────

const args = process.argv.slice(2)
if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
  console.log(`
📦 Template Platform — Module Scaffolding v2.0

Usage:
  node scripts/scaffold-module.mjs <module-name> [options]

Options:
  --functions, -f   Comma-separated list of function pages to create
  --from <starter>  Copiar estrutura de um módulo starter existente

Starters disponíveis (packages/module-starters/):
  _template       Template mínimo
  exemplo         CRUD de referência completo
  etl             Pipeline ETL
  lgpd            Privacidade/LGPD
  observability   Métricas e logs
  docs            Documentação interna

Examples:
  node scripts/scaffold-module.mjs financeiro
  node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios
  node scripts/scaffold-module.mjs clientes --from exemplo
  node scripts/scaffold-module.mjs telemetria --from observability

Generated structure (from scratch):
  apps/web/config/modules/<module>.manifest.ts
  apps/web/app/api/<module>/route.ts
  apps/web/app/(authenticated)/<module>/page.tsx
  apps/web/services/<module>.ts
  apps/web/hooks/use<Module>.ts
  apps/web/schemas/<module>.ts
`)
  process.exit(0)
}

const moduleName = args[0]
const fromFlag = args.indexOf('--from')
const fromStarter = fromFlag !== -1 ? args[fromFlag + 1] : null
const functionsFlag = args.indexOf('--functions') !== -1 ? args.indexOf('--functions') : args.indexOf('-f')
const functions = functionsFlag !== -1 && args[functionsFlag + 1]
  ? args[functionsFlag + 1].split(',').map(f => f.trim()).filter(Boolean)
  : []

const kebab = kebabCase(moduleName)
const pascal = pascalCase(moduleName)

console.log(`\n🚀 Scaffolding module: ${pascal} (${kebab})`)
if (fromStarter) console.log(`   Base: starter '${fromStarter}'`)
if (functions.length > 0) console.log(`   Functions: ${functions.join(', ')}`)
console.log()

// ── Se --from, copiar do starter e registrar ──
if (fromStarter) {
  const copied = copyFromStarter(fromStarter, moduleName)
  if (copied) {
    addToModulesConfig(moduleName)
    addToModulesIndex(moduleName)
    // E2E stub
    const e2eDir = path.join(WEB_ROOT, '..', '..', 'e2e')
    createDir(e2eDir)
    writeFile(path.join(e2eDir, `${kebab}.spec.ts`), e2eStubTemplate(moduleName))

    console.log(`\n✅ Module "${pascal}" criado a partir do starter '${fromStarter}'!`)
    console.log(`\n📝 Next steps:`)
    console.log(`   1. Revisar manifest em apps/web/config/modules/${kebab}.manifest.ts`)
    console.log(`   2. Ativar em apps/web/modules.config.ts (enabled: true)`)
    console.log(`   3. Adaptar páginas e componentes para seu domínio`)
    console.log()
    process.exit(0)
  }
  process.exit(1)
}

// ── Manifest (from scratch) ──
const manifestDir = path.join(WEB_ROOT, 'config', 'modules')
createDir(manifestDir)
writeFile(path.join(manifestDir, `${kebab}.manifest.ts`), manifestTemplate(moduleName))

// ── API Route ──
const apiRouteDir = path.join(WEB_ROOT, 'app', 'api', kebab)
createDir(apiRouteDir)
writeFile(path.join(apiRouteDir, 'route.ts'), apiRouteTemplate(moduleName))

// ── modules.config.ts entry ──
addToModulesConfig(moduleName)

// Create app route directory (Next.js App Router)
const appRouteDir = path.join(WEB_ROOT, 'app', '(authenticated)', kebab)
createDir(appRouteDir)

// Main page
writeFile(path.join(appRouteDir, 'page.tsx'), pageTemplate(moduleName))

// Function sub-routes
for (const func of functions) {
  const funcKebab = kebabCase(func)
  const funcDir = path.join(appRouteDir, funcKebab)
  createDir(funcDir)
  writeFile(path.join(funcDir, 'page.tsx'), functionPageTemplate(moduleName, func))
}

// Service (uses @template/shared apiClient)
const servicesDir = path.join(WEB_ROOT, 'services')
createDir(servicesDir)
writeFile(path.join(servicesDir, `${kebab}.ts`), serviceTemplate(moduleName))

// Hook
const hooksDir = path.join(WEB_ROOT, 'hooks')
createDir(hooksDir)
writeFile(path.join(hooksDir, `use${pascal}.ts`), hookTemplate(moduleName))

// Schema
const schemasDir = path.join(WEB_ROOT, 'schemas')
createDir(schemasDir)
writeFile(path.join(schemasDir, `${kebab}.ts`), schemaTemplate(moduleName))

// Test
const testsDir = path.join(WEB_ROOT, '__tests__', kebab)
createDir(testsDir)
writeFile(path.join(testsDir, `${pascal}Page.test.tsx`), testTemplate(moduleName))

// ── Auto-registro em config/modules/index.ts ──
addToModulesIndex(moduleName)

// ── E2E stub ──
const e2eDir = path.join(WEB_ROOT, '..', '..', 'e2e')
createDir(e2eDir)
writeFile(path.join(e2eDir, `${kebab}.spec.ts`), e2eStubTemplate(moduleName))

console.log(`\n✅ Module "${pascal}" scaffolded successfully!`)
console.log(`\n📝 Next steps:`)
console.log(`   1. Editar manifest em apps/web/config/modules/${kebab}.manifest.ts`)
console.log(`   2. Ativar modulo em apps/web/modules.config.ts (enabled: true)`)
console.log(`   3. Implementar service em apps/web/services/${kebab}.ts`)
console.log(`   4. Implementar API em apps/web/app/api/${kebab}/route.ts`)
console.log(`   5. Customizar schema em apps/web/schemas/${kebab}.ts`)
console.log(`   6. Rodar e2e test: npx playwright test e2e/${kebab}.spec.ts`)
console.log()
