#!/usr/bin/env node
/**
 * CLI Scaffolding — Generate new modules/functions
 * Usage:
 *   node scripts/scaffold-module.mjs <module-name> [--functions func1,func2]
 *
 * Example:
 *   node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WEB_ROOT = path.resolve(__dirname, '..', 'apps', 'web')

function kebabCase(str) {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

function pascalCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function titleCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function createDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
    console.log(`  📁 Created ${path.relative(process.cwd(), dirPath)}`)
  }
}

function writeFile(filePath, content) {
  if (fs.existsSync(filePath)) {
    console.log(`  ⚠️  Skipped (exists): ${path.relative(process.cwd(), filePath)}`)
    return
  }
  fs.writeFileSync(filePath, content, 'utf-8')
  console.log(`  ✅ Created ${path.relative(process.cwd(), filePath)}`)
}

// ── Templates ────────────────────────────────────────────────

function pageTemplate(name) {
  const pascal = pascalCase(name)
  const title = titleCase(name)
  return `/**
 * ${pascal}Page — Auto-generated by scaffold-module
 */
export default function ${pascal}Page() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">${title}</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">
          Pagina do modulo ${title}
        </p>
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">
          Conteudo do modulo ${title}. Implemente sua logica aqui.
        </p>
      </div>
    </div>
  )
}
`
}

function testTemplate(name) {
  const pascal = pascalCase(name)
  return `import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import ${pascal}Page from './${pascal}Page'

describe('${pascal}Page', () => {
  it('renders page title', () => {
    render(<${pascal}Page />)
    expect(screen.getByText('${titleCase(name)}')).toBeInTheDocument()
  })
})
`
}

function serviceTemplate(name) {
  const kebab = kebabCase(name)
  return `/**
 * ${pascalCase(name)} Service — API client
 * Auto-generated by scaffold-module
 */
import { apiClient } from '@template/shared'

const BASE = '/${kebab}'

export const ${kebabCase(name).replace(/-/g, '')}Service = {
  async list(params?: Record<string, string>) {
    const { data } = await apiClient.get(BASE, { params })
    return data
  },

  async getById(id: string) {
    const { data } = await apiClient.get(\`\${BASE}/\${id}\`)
    return data
  },

  async create(payload: Record<string, unknown>) {
    const { data } = await apiClient.post(BASE, payload)
    return data
  },

  async update(id: string, payload: Record<string, unknown>) {
    const { data } = await apiClient.patch(\`\${BASE}/\${id}\`, payload)
    return data
  },

  async remove(id: string) {
    const { data } = await apiClient.delete(\`\${BASE}/\${id}\`)
    return data
  },
}
`
}

function hookTemplate(name) {
  const pascal = pascalCase(name)
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1)
  return `/**
 * use${pascal} — TanStack Query hooks
 * Auto-generated by scaffold-module
 */
import { useQuery } from '@tanstack/react-query'
import { ${kebabCase(name).replace(/-/g, '')}Service } from '@/services/${kebabCase(name)}'

export function use${pascal}List(params?: Record<string, string>) {
  return useQuery({
    queryKey: ['${camel}', 'list', params],
    queryFn: () => ${kebabCase(name).replace(/-/g, '')}Service.list(params),
  })
}

export function use${pascal}ById(id: string | null) {
  return useQuery({
    queryKey: ['${camel}', 'detail', id],
    queryFn: () => ${kebabCase(name).replace(/-/g, '')}Service.getById(id!),
    enabled: !!id,
  })
}
`
}

function schemaTemplate(name) {
  const pascal = pascalCase(name)
  return `/**
 * ${pascal} Zod schemas
 * Auto-generated by scaffold-module
 * Canonical source — re-export via @template/shared if needed cross-app.
 */
import { z } from 'zod'

export const ${pascal}CreateSchema = z.object({
  // Define your fields here
  name: z.string().min(1, 'Nome e obrigatorio').max(255).trim(),
})

export const ${pascal}UpdateSchema = ${pascal}CreateSchema.partial()

export type ${pascal}CreateInput = z.infer<typeof ${pascal}CreateSchema>
export type ${pascal}UpdateInput = z.infer<typeof ${pascal}UpdateSchema>
`
}

function functionPageTemplate(moduleName, funcName) {
  const modulePascal = pascalCase(moduleName)
  const funcPascal = pascalCase(funcName)
  const funcTitle = titleCase(funcName)
  return `/**
 * ${modulePascal} > ${funcPascal} — Auto-generated
 */
export default function ${modulePascal}${funcPascal}Page() {
  return (
    <div className="space-y-4">
      <h2 className="text-xl font-semibold text-gray-900 dark:text-white">${funcTitle}</h2>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">Conteudo de ${funcTitle}.</p>
      </div>
    </div>
  )
}
`
}

// ── Main ─────────────────────────────────────────────────────

const args = process.argv.slice(2)
if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
  console.log(`
📦 Template Platform — Module Scaffolding

Usage:
  node scripts/scaffold-module.mjs <module-name> [--functions func1,func2,func3]

Options:
  --functions, -f   Comma-separated list of function pages to create

Example:
  node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios

Generated structure:
  apps/web/app/(authenticated)/<module>/
    ├── page.tsx (main module page)
    └── <function>/page.tsx (for each function)
  apps/web/services/<module>.ts
  apps/web/hooks/use<Module>.ts
  apps/web/schemas/<module>.ts
`)
  process.exit(0)
}

const moduleName = args[0]
const functionsFlag = args.indexOf('--functions') !== -1 ? args.indexOf('--functions') : args.indexOf('-f')
const functions = functionsFlag !== -1 && args[functionsFlag + 1]
  ? args[functionsFlag + 1].split(',').map(f => f.trim()).filter(Boolean)
  : []

const kebab = kebabCase(moduleName)
const pascal = pascalCase(moduleName)

console.log(`\n🚀 Scaffolding module: ${pascal} (${kebab})`)
if (functions.length > 0) {
  console.log(`   Functions: ${functions.join(', ')}`)
}
console.log()

// Create app route directory (Next.js App Router)
const appRouteDir = path.join(WEB_ROOT, 'app', '(authenticated)', kebab)
createDir(appRouteDir)

// Main page
writeFile(path.join(appRouteDir, 'page.tsx'), pageTemplate(moduleName))

// Function sub-routes
for (const func of functions) {
  const funcKebab = kebabCase(func)
  const funcDir = path.join(appRouteDir, funcKebab)
  createDir(funcDir)
  writeFile(path.join(funcDir, 'page.tsx'), functionPageTemplate(moduleName, func))
}

// Service (uses @template/shared apiClient)
const servicesDir = path.join(WEB_ROOT, 'services')
createDir(servicesDir)
writeFile(path.join(servicesDir, `${kebab}.ts`), serviceTemplate(moduleName))

// Hook
const hooksDir = path.join(WEB_ROOT, 'hooks')
createDir(hooksDir)
writeFile(path.join(hooksDir, `use${pascal}.ts`), hookTemplate(moduleName))

// Schema
const schemasDir = path.join(WEB_ROOT, 'schemas')
createDir(schemasDir)
writeFile(path.join(schemasDir, `${kebab}.ts`), schemaTemplate(moduleName))

// Test
const testsDir = path.join(WEB_ROOT, '__tests__', kebab)
createDir(testsDir)
writeFile(path.join(testsDir, `${pascal}Page.test.tsx`), testTemplate(moduleName))

console.log(`\n✅ Module "${pascal}" scaffolded successfully!`)
console.log(`\n📝 Next steps:`)
console.log(`   1. Add route link to navigation in apps/web/components/`)
console.log(`   2. Implement service methods in apps/web/services/${kebab}.ts`)
console.log(`   3. Wire hooks in apps/web/hooks/use${pascal}.ts`)
console.log(`   4. Customize schema in apps/web/schemas/${kebab}.ts`)
console.log()
