#!/usr/bin/env node
/**
 * CLI Scaffolding — Generate new modules/functions
 * Usage:
 *   node scripts/scaffold-module.mjs <module-name> [--functions func1,func2]
 *
 * Example:
 *   node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WEB_SRC = path.resolve(__dirname, '..', 'apps', 'web', 'src')

function kebabCase(str) {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

function pascalCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function titleCase(str) {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function createDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
    console.log(`  📁 Created ${path.relative(process.cwd(), dirPath)}`)
  }
}

function writeFile(filePath, content) {
  if (fs.existsSync(filePath)) {
    console.log(`  ⚠️  Skipped (exists): ${path.relative(process.cwd(), filePath)}`)
    return
  }
  fs.writeFileSync(filePath, content, 'utf-8')
  console.log(`  ✅ Created ${path.relative(process.cwd(), filePath)}`)
}

// ── Templates ────────────────────────────────────────────────

function pageTemplate(name) {
  const pascal = pascalCase(name)
  const title = titleCase(name)
  return `/**
 * ${pascal}Page — Auto-generated by scaffold-module
 */
export default function ${pascal}Page() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">${title}</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">
          Página do módulo ${title}
        </p>
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">
          Conteúdo do módulo ${title}. Implemente sua lógica aqui.
        </p>
      </div>
    </div>
  )
}
`
}

function testTemplate(name) {
  const pascal = pascalCase(name)
  return `import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import ${pascal}Page from './${pascal}Page'

describe('${pascal}Page', () => {
  it('renders page title', () => {
    render(<${pascal}Page />)
    expect(screen.getByText('${titleCase(name)}')).toBeInTheDocument()
  })
})
`
}

function serviceTemplate(name) {
  const kebab = kebabCase(name)
  return `/**
 * ${pascalCase(name)} Service — API client
 * Auto-generated by scaffold-module
 */
import { apiClient } from './api-client'

const BASE = '/${kebab}'

export const ${kebabCase(name).replace(/-/g, '')}Service = {
  async list(params?: Record<string, string>) {
    const { data } = await apiClient.get(BASE, { params })
    return data
  },

  async getById(id: string) {
    const { data } = await apiClient.get(\`\${BASE}/\${id}\`)
    return data
  },

  async create(payload: Record<string, unknown>) {
    const { data } = await apiClient.post(BASE, payload)
    return data
  },

  async update(id: string, payload: Record<string, unknown>) {
    const { data } = await apiClient.patch(\`\${BASE}/\${id}\`, payload)
    return data
  },

  async remove(id: string) {
    const { data } = await apiClient.delete(\`\${BASE}/\${id}\`)
    return data
  },
}
`
}

function hookTemplate(name) {
  const pascal = pascalCase(name)
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1)
  return `/**
 * use${pascal} — TanStack Query hooks
 * Auto-generated by scaffold-module
 */
import { useQuery } from '@tanstack/react-query'

export function use${pascal}List(params?: Record<string, string>) {
  return useQuery({
    queryKey: ['${camel}', 'list', params],
    queryFn: async () => {
      // Replace with real service call
      return [] as unknown[]
    },
  })
}

export function use${pascal}ById(id: string | null) {
  return useQuery({
    queryKey: ['${camel}', 'detail', id],
    queryFn: async () => {
      // Replace with real service call
      return null
    },
    enabled: !!id,
  })
}
`
}

function functionPageTemplate(moduleName, funcName) {
  const modulePascal = pascalCase(moduleName)
  const funcPascal = pascalCase(funcName)
  const funcTitle = titleCase(funcName)
  return `/**
 * ${modulePascal} > ${funcPascal} — Auto-generated
 */
export default function ${modulePascal}${funcPascal}Page() {
  return (
    <div className="space-y-4">
      <h2 className="text-xl font-semibold text-gray-900 dark:text-white">${funcTitle}</h2>
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300">Conteúdo de ${funcTitle}.</p>
      </div>
    </div>
  )
}
`
}

// ── Main ─────────────────────────────────────────────────────

const args = process.argv.slice(2)
if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
  console.log(`
📦 Template Platform — Module Scaffolding

Usage:
  node scripts/scaffold-module.mjs <module-name> [--functions func1,func2,func3]

Options:
  --functions, -f   Comma-separated list of function pages to create

Example:
  node scripts/scaffold-module.mjs financeiro --functions receitas,despesas,relatorios

Generated structure:
  apps/web/src/pages/<module>/
    ├── <Module>Page.tsx
    ├── <Module>Page.test.tsx
    └── <Function>Page.tsx (for each function)
  apps/web/src/services/<module>.ts
  apps/web/src/hooks/use<Module>.ts
`)
  process.exit(0)
}

const moduleName = args[0]
const functionsFlag = args.indexOf('--functions') !== -1 ? args.indexOf('--functions') : args.indexOf('-f')
const functions = functionsFlag !== -1 && args[functionsFlag + 1]
  ? args[functionsFlag + 1].split(',').map(f => f.trim()).filter(Boolean)
  : []

const kebab = kebabCase(moduleName)
const pascal = pascalCase(moduleName)

console.log(`\n🚀 Scaffolding module: ${pascal} (${kebab})`)
if (functions.length > 0) {
  console.log(`   Functions: ${functions.join(', ')}`)
}
console.log()

// Create pages directory
const pagesDir = path.join(WEB_SRC, 'pages', kebab)
createDir(pagesDir)

// Main page + test
writeFile(path.join(pagesDir, `${pascal}Page.tsx`), pageTemplate(moduleName))
writeFile(path.join(pagesDir, `${pascal}Page.test.tsx`), testTemplate(moduleName))

// Function pages
for (const func of functions) {
  const funcPascal = pascalCase(func)
  writeFile(
    path.join(pagesDir, `${pascal}${funcPascal}Page.tsx`),
    functionPageTemplate(moduleName, func)
  )
}

// Service
writeFile(path.join(WEB_SRC, 'services', `${kebab}.ts`), serviceTemplate(moduleName))

// Hook
writeFile(path.join(WEB_SRC, 'hooks', `use${pascal}.ts`), hookTemplate(moduleName))

console.log(`\n✅ Module "${pascal}" scaffolded successfully!`)
console.log(`\n📝 Next steps:`)
console.log(`   1. Add route to apps/web/src/App.tsx`)
console.log(`   2. Add module entry to apps/web/src/navigation/map.ts`)
console.log(`   3. Add module config to apps/web/src/config/navigation-default.ts`)
console.log(`   4. Implement service methods in apps/web/src/services/${kebab}.ts`)
console.log(`   5. Wire hooks in apps/web/src/hooks/use${pascal}.ts`)
console.log()
